## Problem solving and Programming 

### Day No  :13
### Date - 16 May '19
### Day objectives :
* Objective 1:
* Objective 2:

###  Password validation 
* should contain atleast one upper case
* lenght in (6,21)
* atleast one special symbol
* should start with upper or lower case 
* should contain atleast one digit 

In [1]:
import re
p='^([(?=.*A-Z)(?=.*a-z)(?=.*0-9)(?=.*-+_.@)]{6,21}$)'
d='pass_123'
if(re.match(p,d)):
    print("match")
else:
    print("not match")

match


### Problem 1: 
#### Problem Statement :Program for Finding the vertex, focus and directrix of a parabola

In [2]:
def par(a,b,c):
    print ("Vertex: (" , (-b / (2 * a)) , ", "
        ,(((4 * a * c) - (b * b)) / (4 * a)) , ")" ) 
          
    print ("Focus: (" , (-b / (2 * a)) , ", "
        , (((4 * a * c) - (b * b) + 1) / (4 * a)) , ")" ) 
      
    print ("Directrix: y="
            , (int)(c - ((b * b) + 1) * 4 * a ))     
    
par(5,3,2)

Vertex: ( -0.3 ,  1.55 )
Focus: ( -0.3 ,  1.6 )
Directrix: y= -198


In [3]:
import re
def check(d):
    p='^[a-z][(?=.*0-9)(?=.*a-z)(?=.*A-Z)(?=.*-_.)]{4,13}[0-9a-z][@][0-9a-z]{3,9}[.][a-z]{2,3}'
    if(re.match(p,d)):
            print("match")
    else:
        print("not match")
check('sunilsriharhsa9@gmail.com')
#check("12hbfuj@mfg.in")

match


In [ ]:
.*[a-z].*

In [1]:
def readFileData(filename):
    f=open(filename,'r')   # with open (filename,'r') as f
    filedata = f.read()
    
    f.close()
    return filedata
readFileData('DataFiles/data.txt')

'Data in line 1\nData in line 2\nData in line 3'

In [3]:
def readFileData(filename):
    with open (filename,'r') as f:
        print(f.read())
    return 
readFileData('DataFiles/data.txt')

Data in line 1
Data in line 2
Data in line 3


In [6]:
def writeIntoFile(filename,data):
    with open(filename,'w') as f:
        f.write(data)
    
    return 
#readFileData('DataFiles/data.txt')
writeIntoFile('DataFiles/data1.txt','w')

### Problem 2: 
#### Problem Statement : 
Define a function to genrate a marks data file for 1300 students such that each mark is in new line .marks in range (0,100)

In [57]:
import random
def marks(filename,n):
        with open (filename,'w') as f:
            for i in range(0,n):
                marks=random.randint(1,100)
                f.write(str(marks)+'\n')
marks('DataFiles/marks',1300)

### Problem 3: 
#### Problem Statement : Generation of report with 
* HIGHEST MARK
* LOWEST MARK
* AVG MARK
* NO OF STUDENTS WITH DISTINCTION
* NO OF STUDENTS WITH FIRST CLASS
* NO OF STUDENTS WITH SECOND CLASS
* NO OF STUDENTS WITH THIRD CLASS
* NO OF STUDENTS FAIL 

In [2]:
def reading(filename):
    marks_array=[ ]
    with open (filename,'r') as f:
        for x in f:
            marks_array.append(int(x))
    calculating(marks_array)
def calculating(marks_array):
    for i in range(1,len(marks_array)):
        maxi=max(marks_array)
        mini=min(marks_array)
        avg=sum(marks_array)//len(marks_array)
    dc=0
    fc=0
    sc=0
    tc=0
    fa=0
    for i in range(1,len(marks_array)):
        if(marks_array[i]>=80): dc=dc+1
        if(marks_array[i]>=60 and marks_array[i]<80): fc=fc+1
        if(marks_array[i]>=50 and marks_array[i]<60): sc=sc+1
        if(marks_array[i]>=40 and marks_array[i]<50): tc=tc+1
        if(40>marks_array[i]): fa=fa+1
    #print(marks_array)
    display('DataFiles/report',maxi,mini,avg,dc,fc,sc,tc,fa)
def display(filename,maxi,mini,avg,dc,fc,sc,tc,fa):
     with open (filename,'w') as f:
            f.write("maximum marks ="+str(maxi) +'\n')
            f.write("minimum marks ="+str(mini) +'\n')
            f.write("average marks ="+str(avg) +'\n')
            f.write("no of students with distinction is  ="+str(dc)+'\n')
            f.write("no of students with first class is  ="+str(fc)+'\n')
            f.write("no of students with second class is  ="+str(sc)+'\n')
            f.write("no of students with third class is  ="+str(tc)+'\n')
            f.write("no of students with fail is  ="+str(fa)+'\n')
            return 
reading('DataFiles/marks')

In [245]:
import timeit
start=timeit.default_timer()
def square(n):
    return n*n
li=[1,2,3,4,5,6]
#s=str(li)
x=list(map(square,li))
x
print((timeit.default_timer())-start)

0.00017691099856165238


In [5]:
import numpy as np 
a=np.array([[0,1,2],[3,4,5]])
b=([[5,5,5],[6,6,6]])
print(a)
print(type(a))
print(b)
type(b)

[[0 1 2]
 [3 4 5]]
<class 'numpy.ndarray'>
[[5, 5, 5], [6, 6, 6]]


list

In [8]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[4,5,6]])
print('a=',a)
print('b=',b)
c=a*b
print("a*b=")
c

a= [[1 2 3]
 [4 5 6]]
b= [[1 2 3]
 [4 5 6]]
a*b=


array([[ 1,  4,  9],
       [16, 25, 36]])